const Addons = [
    {
        id: 1,
        img1: "",
        img2: "",
        name: "Monogram Core",
        href: "https://monogramcc.com/shop/products/monogram-core/",
        price: "$149",
        preOrder: true,
    },
    {
        id: 2,
        img1: "",
        img2: "",
        name: "Orbiter Module",
        href: "https://monogramcc.com/shop/products/orbiter-module/",
        price: "$149",
        preOrder: true,
    },
    {
        id: 3,
        img1: "",
        img2: "",
        name: "Dial Module",
        href: "https://monogramcc.com/shop/products/dial-module/",
        price: "$99",
        preOrder: true,
    },
    {
        id: 4,
        img1: "",
        img2: "",
        name: "Slider Module",
        href: "https://monogramcc.com/shop/products/slider-module/",
        price: "$149",
        preOrder: true,
    },
    {
        id: 5,
        img1: "",
        img2: "",
        name: "Essential Keys Module",
        href: "https://monogramcc.com/shop/products/essential-keys-module/",
        price: "$99",
        preOrder: true,
    },
    {
        id: 6,
        img1: "",
        img2: "",
        name: "Console Upgrade: Audio",
        href: "https://monogramcc.com/shop/products/mini-console-upgrade-midi/",
        price: "$29",
        preOrder: true,
    },
    {
        id: 7,
        img1: "",
        img2: "",
        name: "Console Upgrade: Photo",
        href: "https://monogramcc.com/shop/products/mini-console-upgrade-photo/",
        price: "$39",
        preOrder: true,
    },
    {
        id: 8,
        img1: "",
        img2: "",
        name: "Console Upgrade: Video",
        href: "https://monogramcc.com/shop/products/mini-console-upgrade-video/",
        price: "$69",
        preOrder: true,
    },
    {
        id: 9,
        img1: "",
        img2: "",
        name: "Monogram Care",
        href: "https://monogramcc.com/shop/products/dial-module/",
        price: "$19 - $129",
        preOrder: true,
    }
]

export default Addons;